@baseUrl = http://127.0.0.1:8000

### 1️⃣ Crear Job
POST {{baseUrl}}/jobs
Content-Type: application/json

{
  "type": "test_callback",
  "callback_url": "https://httpbin.org/post",
  "payload": {
    "hello": "world"
  },
  "max_retries": 3,
  "priority": 1
}

###

POST {{baseUrl}}/jobs
Content-Type: application/json

{
  "type": "fail_test",
  "callback_url": "http://localhost:9999/nope",
  "payload": {},
  "max_retries": 2
}


### 2️⃣ Obtener Job por ID
# ⚠️ Reemplazá {{jobId}} por el id devuelto en el POST
GET {{baseUrl}}/jobs

###

### 3️⃣ Obtener Timeline del Job
GET {{baseUrl}}/jobs/eafad3e5-67eb-48b0-97a9-b730a1171878k/timeline
